### ISSUE TITLE
Just for reference

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/teamspeak-3_ynh#1]
Hi @liberodark 
I saw you are going to start teamspeak 3 for yunohost. There are other repo for it and I remember it was working too. I don't know current status of those repos. But you can fork them to code less.

https://github.com/inrepublica/teamspeak3_ynh
https://github.com/MidgetMob/ts3server_ynh

**Comment by liberodark** [comment]
ok thx :D but i like create my app and add on official community repo
