### ISSUE TITLE
Check if port is already used by other app

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/teamspeak-3_ynh#2]
Hi
The is preferred to not to ask about the ports while installation and use port=$(ynh_find_port 9987) helper to check if the port is not taken by any other app. This will check the port and increment by 1 till it finds a free port. In the end the port to communicate can be send by email to the admin. 

https://github.com/YunoHost-Apps/teamspeak-3_ynh/blob/master/scripts/install#L65
You can save the ports too for future reference.

**Comment by liberodark** [comment]
is a beta : https://github.com/YunoHost-Apps/teamspeak-3_ynh/blob/Beta/scripts/install
Master is not a good version my version is beta

**Comment by liberodark** [comment]
port=$(ynh_find_port 9987)
